version: "3.7"

services:

  fastapi:
    build: .
    command: "uvicorn main:app --reload"

  mysql:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my_secret_pw


